//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UITalmaNET.srvSeguridad {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="beUsuario", Namespace="http://schemas.datacontract.org/2004/07/EsquemaEntidades.Perfiles", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class beUsuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AL_USUAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AM_USUAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AP_USUAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CO_USUAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NO_USUAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PW_USUAField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AL_USUA {
            get {
                return this.AL_USUAField;
            }
            set {
                if ((object.ReferenceEquals(this.AL_USUAField, value) != true)) {
                    this.AL_USUAField = value;
                    this.RaisePropertyChanged("AL_USUA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AM_USUA {
            get {
                return this.AM_USUAField;
            }
            set {
                if ((object.ReferenceEquals(this.AM_USUAField, value) != true)) {
                    this.AM_USUAField = value;
                    this.RaisePropertyChanged("AM_USUA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AP_USUA {
            get {
                return this.AP_USUAField;
            }
            set {
                if ((object.ReferenceEquals(this.AP_USUAField, value) != true)) {
                    this.AP_USUAField = value;
                    this.RaisePropertyChanged("AP_USUA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CO_USUA {
            get {
                return this.CO_USUAField;
            }
            set {
                if ((object.ReferenceEquals(this.CO_USUAField, value) != true)) {
                    this.CO_USUAField = value;
                    this.RaisePropertyChanged("CO_USUA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NO_USUA {
            get {
                return this.NO_USUAField;
            }
            set {
                if ((object.ReferenceEquals(this.NO_USUAField, value) != true)) {
                    this.NO_USUAField = value;
                    this.RaisePropertyChanged("NO_USUA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PW_USUA {
            get {
                return this.PW_USUAField;
            }
            set {
                if ((object.ReferenceEquals(this.PW_USUAField, value) != true)) {
                    this.PW_USUAField = value;
                    this.RaisePropertyChanged("PW_USUA");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="srvSeguridad.IsrvSeguridad")]
    public interface IsrvSeguridad {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvSeguridad/Valida_Usuario", ReplyAction="http://tempuri.org/IsrvSeguridad/Valida_UsuarioResponse")]
        UITalmaNET.srvSeguridad.beUsuario Valida_Usuario(string AL_USUA, string PW_USUA);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IsrvSeguridadChannel : UITalmaNET.srvSeguridad.IsrvSeguridad, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IsrvSeguridadClient : System.ServiceModel.ClientBase<UITalmaNET.srvSeguridad.IsrvSeguridad>, UITalmaNET.srvSeguridad.IsrvSeguridad {
        
        public IsrvSeguridadClient() {
        }
        
        public IsrvSeguridadClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IsrvSeguridadClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IsrvSeguridadClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IsrvSeguridadClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public UITalmaNET.srvSeguridad.beUsuario Valida_Usuario(string AL_USUA, string PW_USUA) {
            return base.Channel.Valida_Usuario(AL_USUA, PW_USUA);
        }
    }
}
