//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UITalmaNET.srvPreDespacho {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="bePreDespacho", Namespace="http://schemas.datacontract.org/2004/07/EsquemaEntidades.PreDespacho", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class bePreDespacho : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CO_AGENTE_ADUAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CO_CONSIGNATARIOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CO_SEMAFOROField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CO_USUA_CREAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CO_USUA_MODIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FE_FIN_DOCU_ADUAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FE_FIN_LEVANTEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FE_FIN_PREFACTURAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FE_FIN_PRE_DESPACHOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FE_INI_DOCU_ADUAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FE_INI_LEVANTEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FE_INI_PREFACTURAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FE_INI_PRE_DESPACHOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FE_USUA_CREAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FE_USUA_MODIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ID_GUIAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double IM_DEBEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double IM_DEBE_DOLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double IM_DEPOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double IM_DEPO_DOLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double KG_ADUAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double KG_RECIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NO_ENTI_CONCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NU_BULT_ADUAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NU_BULT_RECIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double NU_CIFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NU_DUA_LEVANTEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OB_DOCU_ADUAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OB_LEVANTEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OB_PREFACTURAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ST_DOCU_ADUAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ST_LEVANTEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ST_PREFACTURAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ST_PRE_DESPACHOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ST_SUNAT_LEVANTEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TI_AGENTE_ADUAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TI_CONSIGNATARIOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CO_AGENTE_ADUA {
            get {
                return this.CO_AGENTE_ADUAField;
            }
            set {
                if ((object.ReferenceEquals(this.CO_AGENTE_ADUAField, value) != true)) {
                    this.CO_AGENTE_ADUAField = value;
                    this.RaisePropertyChanged("CO_AGENTE_ADUA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CO_CONSIGNATARIO {
            get {
                return this.CO_CONSIGNATARIOField;
            }
            set {
                if ((object.ReferenceEquals(this.CO_CONSIGNATARIOField, value) != true)) {
                    this.CO_CONSIGNATARIOField = value;
                    this.RaisePropertyChanged("CO_CONSIGNATARIO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CO_SEMAFORO {
            get {
                return this.CO_SEMAFOROField;
            }
            set {
                if ((object.ReferenceEquals(this.CO_SEMAFOROField, value) != true)) {
                    this.CO_SEMAFOROField = value;
                    this.RaisePropertyChanged("CO_SEMAFORO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CO_USUA_CREA {
            get {
                return this.CO_USUA_CREAField;
            }
            set {
                if ((object.ReferenceEquals(this.CO_USUA_CREAField, value) != true)) {
                    this.CO_USUA_CREAField = value;
                    this.RaisePropertyChanged("CO_USUA_CREA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CO_USUA_MODI {
            get {
                return this.CO_USUA_MODIField;
            }
            set {
                if ((object.ReferenceEquals(this.CO_USUA_MODIField, value) != true)) {
                    this.CO_USUA_MODIField = value;
                    this.RaisePropertyChanged("CO_USUA_MODI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FE_FIN_DOCU_ADUA {
            get {
                return this.FE_FIN_DOCU_ADUAField;
            }
            set {
                if ((this.FE_FIN_DOCU_ADUAField.Equals(value) != true)) {
                    this.FE_FIN_DOCU_ADUAField = value;
                    this.RaisePropertyChanged("FE_FIN_DOCU_ADUA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FE_FIN_LEVANTE {
            get {
                return this.FE_FIN_LEVANTEField;
            }
            set {
                if ((this.FE_FIN_LEVANTEField.Equals(value) != true)) {
                    this.FE_FIN_LEVANTEField = value;
                    this.RaisePropertyChanged("FE_FIN_LEVANTE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FE_FIN_PREFACTURA {
            get {
                return this.FE_FIN_PREFACTURAField;
            }
            set {
                if ((this.FE_FIN_PREFACTURAField.Equals(value) != true)) {
                    this.FE_FIN_PREFACTURAField = value;
                    this.RaisePropertyChanged("FE_FIN_PREFACTURA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FE_FIN_PRE_DESPACHO {
            get {
                return this.FE_FIN_PRE_DESPACHOField;
            }
            set {
                if ((this.FE_FIN_PRE_DESPACHOField.Equals(value) != true)) {
                    this.FE_FIN_PRE_DESPACHOField = value;
                    this.RaisePropertyChanged("FE_FIN_PRE_DESPACHO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FE_INI_DOCU_ADUA {
            get {
                return this.FE_INI_DOCU_ADUAField;
            }
            set {
                if ((this.FE_INI_DOCU_ADUAField.Equals(value) != true)) {
                    this.FE_INI_DOCU_ADUAField = value;
                    this.RaisePropertyChanged("FE_INI_DOCU_ADUA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FE_INI_LEVANTE {
            get {
                return this.FE_INI_LEVANTEField;
            }
            set {
                if ((this.FE_INI_LEVANTEField.Equals(value) != true)) {
                    this.FE_INI_LEVANTEField = value;
                    this.RaisePropertyChanged("FE_INI_LEVANTE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FE_INI_PREFACTURA {
            get {
                return this.FE_INI_PREFACTURAField;
            }
            set {
                if ((this.FE_INI_PREFACTURAField.Equals(value) != true)) {
                    this.FE_INI_PREFACTURAField = value;
                    this.RaisePropertyChanged("FE_INI_PREFACTURA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FE_INI_PRE_DESPACHO {
            get {
                return this.FE_INI_PRE_DESPACHOField;
            }
            set {
                if ((this.FE_INI_PRE_DESPACHOField.Equals(value) != true)) {
                    this.FE_INI_PRE_DESPACHOField = value;
                    this.RaisePropertyChanged("FE_INI_PRE_DESPACHO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FE_USUA_CREA {
            get {
                return this.FE_USUA_CREAField;
            }
            set {
                if ((this.FE_USUA_CREAField.Equals(value) != true)) {
                    this.FE_USUA_CREAField = value;
                    this.RaisePropertyChanged("FE_USUA_CREA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FE_USUA_MODI {
            get {
                return this.FE_USUA_MODIField;
            }
            set {
                if ((this.FE_USUA_MODIField.Equals(value) != true)) {
                    this.FE_USUA_MODIField = value;
                    this.RaisePropertyChanged("FE_USUA_MODI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID_GUIA {
            get {
                return this.ID_GUIAField;
            }
            set {
                if ((object.ReferenceEquals(this.ID_GUIAField, value) != true)) {
                    this.ID_GUIAField = value;
                    this.RaisePropertyChanged("ID_GUIA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double IM_DEBE {
            get {
                return this.IM_DEBEField;
            }
            set {
                if ((this.IM_DEBEField.Equals(value) != true)) {
                    this.IM_DEBEField = value;
                    this.RaisePropertyChanged("IM_DEBE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double IM_DEBE_DOL {
            get {
                return this.IM_DEBE_DOLField;
            }
            set {
                if ((this.IM_DEBE_DOLField.Equals(value) != true)) {
                    this.IM_DEBE_DOLField = value;
                    this.RaisePropertyChanged("IM_DEBE_DOL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double IM_DEPO {
            get {
                return this.IM_DEPOField;
            }
            set {
                if ((this.IM_DEPOField.Equals(value) != true)) {
                    this.IM_DEPOField = value;
                    this.RaisePropertyChanged("IM_DEPO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double IM_DEPO_DOL {
            get {
                return this.IM_DEPO_DOLField;
            }
            set {
                if ((this.IM_DEPO_DOLField.Equals(value) != true)) {
                    this.IM_DEPO_DOLField = value;
                    this.RaisePropertyChanged("IM_DEPO_DOL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double KG_ADUA {
            get {
                return this.KG_ADUAField;
            }
            set {
                if ((this.KG_ADUAField.Equals(value) != true)) {
                    this.KG_ADUAField = value;
                    this.RaisePropertyChanged("KG_ADUA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double KG_RECI {
            get {
                return this.KG_RECIField;
            }
            set {
                if ((this.KG_RECIField.Equals(value) != true)) {
                    this.KG_RECIField = value;
                    this.RaisePropertyChanged("KG_RECI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NO_ENTI_CONC {
            get {
                return this.NO_ENTI_CONCField;
            }
            set {
                if ((object.ReferenceEquals(this.NO_ENTI_CONCField, value) != true)) {
                    this.NO_ENTI_CONCField = value;
                    this.RaisePropertyChanged("NO_ENTI_CONC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NU_BULT_ADUA {
            get {
                return this.NU_BULT_ADUAField;
            }
            set {
                if ((this.NU_BULT_ADUAField.Equals(value) != true)) {
                    this.NU_BULT_ADUAField = value;
                    this.RaisePropertyChanged("NU_BULT_ADUA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NU_BULT_RECI {
            get {
                return this.NU_BULT_RECIField;
            }
            set {
                if ((this.NU_BULT_RECIField.Equals(value) != true)) {
                    this.NU_BULT_RECIField = value;
                    this.RaisePropertyChanged("NU_BULT_RECI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double NU_CIF {
            get {
                return this.NU_CIFField;
            }
            set {
                if ((this.NU_CIFField.Equals(value) != true)) {
                    this.NU_CIFField = value;
                    this.RaisePropertyChanged("NU_CIF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NU_DUA_LEVANTE {
            get {
                return this.NU_DUA_LEVANTEField;
            }
            set {
                if ((object.ReferenceEquals(this.NU_DUA_LEVANTEField, value) != true)) {
                    this.NU_DUA_LEVANTEField = value;
                    this.RaisePropertyChanged("NU_DUA_LEVANTE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OB_DOCU_ADUA {
            get {
                return this.OB_DOCU_ADUAField;
            }
            set {
                if ((object.ReferenceEquals(this.OB_DOCU_ADUAField, value) != true)) {
                    this.OB_DOCU_ADUAField = value;
                    this.RaisePropertyChanged("OB_DOCU_ADUA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OB_LEVANTE {
            get {
                return this.OB_LEVANTEField;
            }
            set {
                if ((object.ReferenceEquals(this.OB_LEVANTEField, value) != true)) {
                    this.OB_LEVANTEField = value;
                    this.RaisePropertyChanged("OB_LEVANTE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OB_PREFACTURA {
            get {
                return this.OB_PREFACTURAField;
            }
            set {
                if ((object.ReferenceEquals(this.OB_PREFACTURAField, value) != true)) {
                    this.OB_PREFACTURAField = value;
                    this.RaisePropertyChanged("OB_PREFACTURA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ST_DOCU_ADUA {
            get {
                return this.ST_DOCU_ADUAField;
            }
            set {
                if ((object.ReferenceEquals(this.ST_DOCU_ADUAField, value) != true)) {
                    this.ST_DOCU_ADUAField = value;
                    this.RaisePropertyChanged("ST_DOCU_ADUA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ST_LEVANTE {
            get {
                return this.ST_LEVANTEField;
            }
            set {
                if ((object.ReferenceEquals(this.ST_LEVANTEField, value) != true)) {
                    this.ST_LEVANTEField = value;
                    this.RaisePropertyChanged("ST_LEVANTE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ST_PREFACTURA {
            get {
                return this.ST_PREFACTURAField;
            }
            set {
                if ((object.ReferenceEquals(this.ST_PREFACTURAField, value) != true)) {
                    this.ST_PREFACTURAField = value;
                    this.RaisePropertyChanged("ST_PREFACTURA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ST_PRE_DESPACHO {
            get {
                return this.ST_PRE_DESPACHOField;
            }
            set {
                if ((object.ReferenceEquals(this.ST_PRE_DESPACHOField, value) != true)) {
                    this.ST_PRE_DESPACHOField = value;
                    this.RaisePropertyChanged("ST_PRE_DESPACHO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ST_SUNAT_LEVANTE {
            get {
                return this.ST_SUNAT_LEVANTEField;
            }
            set {
                if ((object.ReferenceEquals(this.ST_SUNAT_LEVANTEField, value) != true)) {
                    this.ST_SUNAT_LEVANTEField = value;
                    this.RaisePropertyChanged("ST_SUNAT_LEVANTE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TI_AGENTE_ADUA {
            get {
                return this.TI_AGENTE_ADUAField;
            }
            set {
                if ((object.ReferenceEquals(this.TI_AGENTE_ADUAField, value) != true)) {
                    this.TI_AGENTE_ADUAField = value;
                    this.RaisePropertyChanged("TI_AGENTE_ADUA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TI_CONSIGNATARIO {
            get {
                return this.TI_CONSIGNATARIOField;
            }
            set {
                if ((object.ReferenceEquals(this.TI_CONSIGNATARIOField, value) != true)) {
                    this.TI_CONSIGNATARIOField = value;
                    this.RaisePropertyChanged("TI_CONSIGNATARIO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="beLogger", Namespace="http://schemas.datacontract.org/2004/07/EsquemaEntidades.Log", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class beLogger : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UITalmaNET.srvPreDespacho.EstadoLogger EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RegistrosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mensaje1Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UITalmaNET.srvPreDespacho.EstadoLogger Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Registros {
            get {
                return this.RegistrosField;
            }
            set {
                if ((this.RegistrosField.Equals(value) != true)) {
                    this.RegistrosField = value;
                    this.RaisePropertyChanged("Registros");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="mensaje")]
        public string mensaje1 {
            get {
                return this.mensaje1Field;
            }
            set {
                if ((object.ReferenceEquals(this.mensaje1Field, value) != true)) {
                    this.mensaje1Field = value;
                    this.RaisePropertyChanged("mensaje1");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EstadoLogger", Namespace="http://schemas.datacontract.org/2004/07/EsquemaEntidades.Log")]
    public enum EstadoLogger : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OK = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ERROR = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="bePreFactura", Namespace="http://schemas.datacontract.org/2004/07/EsquemaEntidades.PreDespacho", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class bePreFactura : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CO_CLIE_FACTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CO_USUA_CREAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DE_DIREField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FE_EMISIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FE_USUA_CREAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ID_GUIAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double IM_DCTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double IM_IGVSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double IM_TOTALField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double IM_TOTAL_DOLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double IM_VENTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NO_CLIE_FACTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NU_DIASField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<UITalmaNET.srvPreDespacho.bePreFactura_Detalle> OB_DETALLEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PC_DCTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PC_IGVSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TI_CAMBField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CO_CLIE_FACT {
            get {
                return this.CO_CLIE_FACTField;
            }
            set {
                if ((object.ReferenceEquals(this.CO_CLIE_FACTField, value) != true)) {
                    this.CO_CLIE_FACTField = value;
                    this.RaisePropertyChanged("CO_CLIE_FACT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CO_USUA_CREA {
            get {
                return this.CO_USUA_CREAField;
            }
            set {
                if ((object.ReferenceEquals(this.CO_USUA_CREAField, value) != true)) {
                    this.CO_USUA_CREAField = value;
                    this.RaisePropertyChanged("CO_USUA_CREA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DE_DIRE {
            get {
                return this.DE_DIREField;
            }
            set {
                if ((object.ReferenceEquals(this.DE_DIREField, value) != true)) {
                    this.DE_DIREField = value;
                    this.RaisePropertyChanged("DE_DIRE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FE_EMISION {
            get {
                return this.FE_EMISIONField;
            }
            set {
                if ((this.FE_EMISIONField.Equals(value) != true)) {
                    this.FE_EMISIONField = value;
                    this.RaisePropertyChanged("FE_EMISION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FE_USUA_CREA {
            get {
                return this.FE_USUA_CREAField;
            }
            set {
                if ((this.FE_USUA_CREAField.Equals(value) != true)) {
                    this.FE_USUA_CREAField = value;
                    this.RaisePropertyChanged("FE_USUA_CREA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID_GUIA {
            get {
                return this.ID_GUIAField;
            }
            set {
                if ((object.ReferenceEquals(this.ID_GUIAField, value) != true)) {
                    this.ID_GUIAField = value;
                    this.RaisePropertyChanged("ID_GUIA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double IM_DCTO {
            get {
                return this.IM_DCTOField;
            }
            set {
                if ((this.IM_DCTOField.Equals(value) != true)) {
                    this.IM_DCTOField = value;
                    this.RaisePropertyChanged("IM_DCTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double IM_IGVS {
            get {
                return this.IM_IGVSField;
            }
            set {
                if ((this.IM_IGVSField.Equals(value) != true)) {
                    this.IM_IGVSField = value;
                    this.RaisePropertyChanged("IM_IGVS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double IM_TOTAL {
            get {
                return this.IM_TOTALField;
            }
            set {
                if ((this.IM_TOTALField.Equals(value) != true)) {
                    this.IM_TOTALField = value;
                    this.RaisePropertyChanged("IM_TOTAL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double IM_TOTAL_DOL {
            get {
                return this.IM_TOTAL_DOLField;
            }
            set {
                if ((this.IM_TOTAL_DOLField.Equals(value) != true)) {
                    this.IM_TOTAL_DOLField = value;
                    this.RaisePropertyChanged("IM_TOTAL_DOL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double IM_VENT {
            get {
                return this.IM_VENTField;
            }
            set {
                if ((this.IM_VENTField.Equals(value) != true)) {
                    this.IM_VENTField = value;
                    this.RaisePropertyChanged("IM_VENT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NO_CLIE_FACT {
            get {
                return this.NO_CLIE_FACTField;
            }
            set {
                if ((object.ReferenceEquals(this.NO_CLIE_FACTField, value) != true)) {
                    this.NO_CLIE_FACTField = value;
                    this.RaisePropertyChanged("NO_CLIE_FACT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NU_DIAS {
            get {
                return this.NU_DIASField;
            }
            set {
                if ((this.NU_DIASField.Equals(value) != true)) {
                    this.NU_DIASField = value;
                    this.RaisePropertyChanged("NU_DIAS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<UITalmaNET.srvPreDespacho.bePreFactura_Detalle> OB_DETALLE {
            get {
                return this.OB_DETALLEField;
            }
            set {
                if ((object.ReferenceEquals(this.OB_DETALLEField, value) != true)) {
                    this.OB_DETALLEField = value;
                    this.RaisePropertyChanged("OB_DETALLE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PC_DCTO {
            get {
                return this.PC_DCTOField;
            }
            set {
                if ((this.PC_DCTOField.Equals(value) != true)) {
                    this.PC_DCTOField = value;
                    this.RaisePropertyChanged("PC_DCTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PC_IGVS {
            get {
                return this.PC_IGVSField;
            }
            set {
                if ((this.PC_IGVSField.Equals(value) != true)) {
                    this.PC_IGVSField = value;
                    this.RaisePropertyChanged("PC_IGVS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double TI_CAMB {
            get {
                return this.TI_CAMBField;
            }
            set {
                if ((this.TI_CAMBField.Equals(value) != true)) {
                    this.TI_CAMBField = value;
                    this.RaisePropertyChanged("TI_CAMB");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="bePreFactura_Detalle", Namespace="http://schemas.datacontract.org/2004/07/EsquemaEntidades.PreDespacho", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class bePreFactura_Detalle : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CO_CPTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CO_USUA_CREAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DE_CPTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FE_USUA_CREAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ID_GUIAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double IM_DCTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double IM_IGVSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double IM_VENTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PC_DCTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PC_IGVSField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CO_CPTO {
            get {
                return this.CO_CPTOField;
            }
            set {
                if ((object.ReferenceEquals(this.CO_CPTOField, value) != true)) {
                    this.CO_CPTOField = value;
                    this.RaisePropertyChanged("CO_CPTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CO_USUA_CREA {
            get {
                return this.CO_USUA_CREAField;
            }
            set {
                if ((object.ReferenceEquals(this.CO_USUA_CREAField, value) != true)) {
                    this.CO_USUA_CREAField = value;
                    this.RaisePropertyChanged("CO_USUA_CREA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DE_CPTO {
            get {
                return this.DE_CPTOField;
            }
            set {
                if ((object.ReferenceEquals(this.DE_CPTOField, value) != true)) {
                    this.DE_CPTOField = value;
                    this.RaisePropertyChanged("DE_CPTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FE_USUA_CREA {
            get {
                return this.FE_USUA_CREAField;
            }
            set {
                if ((this.FE_USUA_CREAField.Equals(value) != true)) {
                    this.FE_USUA_CREAField = value;
                    this.RaisePropertyChanged("FE_USUA_CREA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID_GUIA {
            get {
                return this.ID_GUIAField;
            }
            set {
                if ((object.ReferenceEquals(this.ID_GUIAField, value) != true)) {
                    this.ID_GUIAField = value;
                    this.RaisePropertyChanged("ID_GUIA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double IM_DCTO {
            get {
                return this.IM_DCTOField;
            }
            set {
                if ((this.IM_DCTOField.Equals(value) != true)) {
                    this.IM_DCTOField = value;
                    this.RaisePropertyChanged("IM_DCTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double IM_IGVS {
            get {
                return this.IM_IGVSField;
            }
            set {
                if ((this.IM_IGVSField.Equals(value) != true)) {
                    this.IM_IGVSField = value;
                    this.RaisePropertyChanged("IM_IGVS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double IM_VENT {
            get {
                return this.IM_VENTField;
            }
            set {
                if ((this.IM_VENTField.Equals(value) != true)) {
                    this.IM_VENTField = value;
                    this.RaisePropertyChanged("IM_VENT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PC_DCTO {
            get {
                return this.PC_DCTOField;
            }
            set {
                if ((this.PC_DCTOField.Equals(value) != true)) {
                    this.PC_DCTOField = value;
                    this.RaisePropertyChanged("PC_DCTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PC_IGVS {
            get {
                return this.PC_IGVSField;
            }
            set {
                if ((this.PC_IGVSField.Equals(value) != true)) {
                    this.PC_IGVSField = value;
                    this.RaisePropertyChanged("PC_IGVS");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="beGuia", Namespace="http://schemas.datacontract.org/2004/07/EsquemaEntidades.PreDespacho", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class beGuia : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CO_CIUD_DESField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CO_CIUD_ORIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CO_ENTI_LINEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DE_CONTENIDOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FE_LLEG_VUELField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FE_PRIMER_BULTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ID_GUIAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double KG_RECIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NO_ENTI_AGREField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NO_ENTI_CONCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NO_ENTI_LINEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NU_BULT_RECIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NU_GUIA_HIJAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NU_GUIA_MADRField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NU_MANI_HERField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NU_VUELField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CO_CIUD_DES {
            get {
                return this.CO_CIUD_DESField;
            }
            set {
                if ((object.ReferenceEquals(this.CO_CIUD_DESField, value) != true)) {
                    this.CO_CIUD_DESField = value;
                    this.RaisePropertyChanged("CO_CIUD_DES");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CO_CIUD_ORI {
            get {
                return this.CO_CIUD_ORIField;
            }
            set {
                if ((object.ReferenceEquals(this.CO_CIUD_ORIField, value) != true)) {
                    this.CO_CIUD_ORIField = value;
                    this.RaisePropertyChanged("CO_CIUD_ORI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CO_ENTI_LINE {
            get {
                return this.CO_ENTI_LINEField;
            }
            set {
                if ((object.ReferenceEquals(this.CO_ENTI_LINEField, value) != true)) {
                    this.CO_ENTI_LINEField = value;
                    this.RaisePropertyChanged("CO_ENTI_LINE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DE_CONTENIDO {
            get {
                return this.DE_CONTENIDOField;
            }
            set {
                if ((object.ReferenceEquals(this.DE_CONTENIDOField, value) != true)) {
                    this.DE_CONTENIDOField = value;
                    this.RaisePropertyChanged("DE_CONTENIDO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FE_LLEG_VUEL {
            get {
                return this.FE_LLEG_VUELField;
            }
            set {
                if ((this.FE_LLEG_VUELField.Equals(value) != true)) {
                    this.FE_LLEG_VUELField = value;
                    this.RaisePropertyChanged("FE_LLEG_VUEL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FE_PRIMER_BULTO {
            get {
                return this.FE_PRIMER_BULTOField;
            }
            set {
                if ((this.FE_PRIMER_BULTOField.Equals(value) != true)) {
                    this.FE_PRIMER_BULTOField = value;
                    this.RaisePropertyChanged("FE_PRIMER_BULTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID_GUIA {
            get {
                return this.ID_GUIAField;
            }
            set {
                if ((object.ReferenceEquals(this.ID_GUIAField, value) != true)) {
                    this.ID_GUIAField = value;
                    this.RaisePropertyChanged("ID_GUIA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double KG_RECI {
            get {
                return this.KG_RECIField;
            }
            set {
                if ((this.KG_RECIField.Equals(value) != true)) {
                    this.KG_RECIField = value;
                    this.RaisePropertyChanged("KG_RECI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NO_ENTI_AGRE {
            get {
                return this.NO_ENTI_AGREField;
            }
            set {
                if ((object.ReferenceEquals(this.NO_ENTI_AGREField, value) != true)) {
                    this.NO_ENTI_AGREField = value;
                    this.RaisePropertyChanged("NO_ENTI_AGRE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NO_ENTI_CONC {
            get {
                return this.NO_ENTI_CONCField;
            }
            set {
                if ((object.ReferenceEquals(this.NO_ENTI_CONCField, value) != true)) {
                    this.NO_ENTI_CONCField = value;
                    this.RaisePropertyChanged("NO_ENTI_CONC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NO_ENTI_LINE {
            get {
                return this.NO_ENTI_LINEField;
            }
            set {
                if ((object.ReferenceEquals(this.NO_ENTI_LINEField, value) != true)) {
                    this.NO_ENTI_LINEField = value;
                    this.RaisePropertyChanged("NO_ENTI_LINE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NU_BULT_RECI {
            get {
                return this.NU_BULT_RECIField;
            }
            set {
                if ((this.NU_BULT_RECIField.Equals(value) != true)) {
                    this.NU_BULT_RECIField = value;
                    this.RaisePropertyChanged("NU_BULT_RECI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NU_GUIA_HIJA {
            get {
                return this.NU_GUIA_HIJAField;
            }
            set {
                if ((object.ReferenceEquals(this.NU_GUIA_HIJAField, value) != true)) {
                    this.NU_GUIA_HIJAField = value;
                    this.RaisePropertyChanged("NU_GUIA_HIJA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NU_GUIA_MADR {
            get {
                return this.NU_GUIA_MADRField;
            }
            set {
                if ((object.ReferenceEquals(this.NU_GUIA_MADRField, value) != true)) {
                    this.NU_GUIA_MADRField = value;
                    this.RaisePropertyChanged("NU_GUIA_MADR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NU_MANI_HER {
            get {
                return this.NU_MANI_HERField;
            }
            set {
                if ((object.ReferenceEquals(this.NU_MANI_HERField, value) != true)) {
                    this.NU_MANI_HERField = value;
                    this.RaisePropertyChanged("NU_MANI_HER");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NU_VUEL {
            get {
                return this.NU_VUELField;
            }
            set {
                if ((object.ReferenceEquals(this.NU_VUELField, value) != true)) {
                    this.NU_VUELField = value;
                    this.RaisePropertyChanged("NU_VUEL");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="beTransaccion", Namespace="http://schemas.datacontract.org/2004/07/EsquemaEntidades.PreDespacho", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class beTransaccion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] BT_ARCHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CO_USUA_CREAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CO_USUA_MODIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EX_ARCHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FE_ARCH_UPLOADField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FE_USUA_CREAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FE_USUA_MODIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_ARCHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ID_GUIAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double IM_ARCHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OB_ARCHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RT_ARCH_FILEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RT_ARCH_WEBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ST_ARCHField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] BT_ARCH {
            get {
                return this.BT_ARCHField;
            }
            set {
                if ((object.ReferenceEquals(this.BT_ARCHField, value) != true)) {
                    this.BT_ARCHField = value;
                    this.RaisePropertyChanged("BT_ARCH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CO_USUA_CREA {
            get {
                return this.CO_USUA_CREAField;
            }
            set {
                if ((object.ReferenceEquals(this.CO_USUA_CREAField, value) != true)) {
                    this.CO_USUA_CREAField = value;
                    this.RaisePropertyChanged("CO_USUA_CREA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CO_USUA_MODI {
            get {
                return this.CO_USUA_MODIField;
            }
            set {
                if ((object.ReferenceEquals(this.CO_USUA_MODIField, value) != true)) {
                    this.CO_USUA_MODIField = value;
                    this.RaisePropertyChanged("CO_USUA_MODI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EX_ARCH {
            get {
                return this.EX_ARCHField;
            }
            set {
                if ((object.ReferenceEquals(this.EX_ARCHField, value) != true)) {
                    this.EX_ARCHField = value;
                    this.RaisePropertyChanged("EX_ARCH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FE_ARCH_UPLOAD {
            get {
                return this.FE_ARCH_UPLOADField;
            }
            set {
                if ((this.FE_ARCH_UPLOADField.Equals(value) != true)) {
                    this.FE_ARCH_UPLOADField = value;
                    this.RaisePropertyChanged("FE_ARCH_UPLOAD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FE_USUA_CREA {
            get {
                return this.FE_USUA_CREAField;
            }
            set {
                if ((this.FE_USUA_CREAField.Equals(value) != true)) {
                    this.FE_USUA_CREAField = value;
                    this.RaisePropertyChanged("FE_USUA_CREA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FE_USUA_MODI {
            get {
                return this.FE_USUA_MODIField;
            }
            set {
                if ((this.FE_USUA_MODIField.Equals(value) != true)) {
                    this.FE_USUA_MODIField = value;
                    this.RaisePropertyChanged("FE_USUA_MODI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_ARCH {
            get {
                return this.ID_ARCHField;
            }
            set {
                if ((this.ID_ARCHField.Equals(value) != true)) {
                    this.ID_ARCHField = value;
                    this.RaisePropertyChanged("ID_ARCH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID_GUIA {
            get {
                return this.ID_GUIAField;
            }
            set {
                if ((object.ReferenceEquals(this.ID_GUIAField, value) != true)) {
                    this.ID_GUIAField = value;
                    this.RaisePropertyChanged("ID_GUIA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double IM_ARCH {
            get {
                return this.IM_ARCHField;
            }
            set {
                if ((this.IM_ARCHField.Equals(value) != true)) {
                    this.IM_ARCHField = value;
                    this.RaisePropertyChanged("IM_ARCH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OB_ARCH {
            get {
                return this.OB_ARCHField;
            }
            set {
                if ((object.ReferenceEquals(this.OB_ARCHField, value) != true)) {
                    this.OB_ARCHField = value;
                    this.RaisePropertyChanged("OB_ARCH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RT_ARCH_FILE {
            get {
                return this.RT_ARCH_FILEField;
            }
            set {
                if ((object.ReferenceEquals(this.RT_ARCH_FILEField, value) != true)) {
                    this.RT_ARCH_FILEField = value;
                    this.RaisePropertyChanged("RT_ARCH_FILE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RT_ARCH_WEB {
            get {
                return this.RT_ARCH_WEBField;
            }
            set {
                if ((object.ReferenceEquals(this.RT_ARCH_WEBField, value) != true)) {
                    this.RT_ARCH_WEBField = value;
                    this.RaisePropertyChanged("RT_ARCH_WEB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ST_ARCH {
            get {
                return this.ST_ARCHField;
            }
            set {
                if ((object.ReferenceEquals(this.ST_ARCHField, value) != true)) {
                    this.ST_ARCHField = value;
                    this.RaisePropertyChanged("ST_ARCH");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="bePreDespacho_Documento", Namespace="http://schemas.datacontract.org/2004/07/EsquemaEntidades.PreDespacho", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class bePreDespacho_Documento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] BT_ARCHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CO_USUA_CREAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CO_USUA_MODIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EX_ARCHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FE_ARCH_UPLOADField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FE_USUA_CREAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FE_USUA_MODIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_ARCHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ID_GUIAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OB_ARCHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RT_ARCH_FILEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RT_ARCH_WEBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ST_ARCHField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] BT_ARCH {
            get {
                return this.BT_ARCHField;
            }
            set {
                if ((object.ReferenceEquals(this.BT_ARCHField, value) != true)) {
                    this.BT_ARCHField = value;
                    this.RaisePropertyChanged("BT_ARCH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CO_USUA_CREA {
            get {
                return this.CO_USUA_CREAField;
            }
            set {
                if ((object.ReferenceEquals(this.CO_USUA_CREAField, value) != true)) {
                    this.CO_USUA_CREAField = value;
                    this.RaisePropertyChanged("CO_USUA_CREA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CO_USUA_MODI {
            get {
                return this.CO_USUA_MODIField;
            }
            set {
                if ((object.ReferenceEquals(this.CO_USUA_MODIField, value) != true)) {
                    this.CO_USUA_MODIField = value;
                    this.RaisePropertyChanged("CO_USUA_MODI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EX_ARCH {
            get {
                return this.EX_ARCHField;
            }
            set {
                if ((object.ReferenceEquals(this.EX_ARCHField, value) != true)) {
                    this.EX_ARCHField = value;
                    this.RaisePropertyChanged("EX_ARCH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FE_ARCH_UPLOAD {
            get {
                return this.FE_ARCH_UPLOADField;
            }
            set {
                if ((this.FE_ARCH_UPLOADField.Equals(value) != true)) {
                    this.FE_ARCH_UPLOADField = value;
                    this.RaisePropertyChanged("FE_ARCH_UPLOAD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FE_USUA_CREA {
            get {
                return this.FE_USUA_CREAField;
            }
            set {
                if ((this.FE_USUA_CREAField.Equals(value) != true)) {
                    this.FE_USUA_CREAField = value;
                    this.RaisePropertyChanged("FE_USUA_CREA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FE_USUA_MODI {
            get {
                return this.FE_USUA_MODIField;
            }
            set {
                if ((this.FE_USUA_MODIField.Equals(value) != true)) {
                    this.FE_USUA_MODIField = value;
                    this.RaisePropertyChanged("FE_USUA_MODI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_ARCH {
            get {
                return this.ID_ARCHField;
            }
            set {
                if ((this.ID_ARCHField.Equals(value) != true)) {
                    this.ID_ARCHField = value;
                    this.RaisePropertyChanged("ID_ARCH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID_GUIA {
            get {
                return this.ID_GUIAField;
            }
            set {
                if ((object.ReferenceEquals(this.ID_GUIAField, value) != true)) {
                    this.ID_GUIAField = value;
                    this.RaisePropertyChanged("ID_GUIA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OB_ARCH {
            get {
                return this.OB_ARCHField;
            }
            set {
                if ((object.ReferenceEquals(this.OB_ARCHField, value) != true)) {
                    this.OB_ARCHField = value;
                    this.RaisePropertyChanged("OB_ARCH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RT_ARCH_FILE {
            get {
                return this.RT_ARCH_FILEField;
            }
            set {
                if ((object.ReferenceEquals(this.RT_ARCH_FILEField, value) != true)) {
                    this.RT_ARCH_FILEField = value;
                    this.RaisePropertyChanged("RT_ARCH_FILE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RT_ARCH_WEB {
            get {
                return this.RT_ARCH_WEBField;
            }
            set {
                if ((object.ReferenceEquals(this.RT_ARCH_WEBField, value) != true)) {
                    this.RT_ARCH_WEBField = value;
                    this.RaisePropertyChanged("RT_ARCH_WEB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ST_ARCH {
            get {
                return this.ST_ARCHField;
            }
            set {
                if ((object.ReferenceEquals(this.ST_ARCHField, value) != true)) {
                    this.ST_ARCHField = value;
                    this.RaisePropertyChanged("ST_ARCH");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="srvPreDespacho.IsrvPreDespacho")]
    public interface IsrvPreDespacho {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvPreDespacho/GetPreDespachos", ReplyAction="http://tempuri.org/IsrvPreDespacho/GetPreDespachosResponse")]
        System.Collections.Generic.List<UITalmaNET.srvPreDespacho.bePreDespacho> GetPreDespachos(out UITalmaNET.srvPreDespacho.beLogger logger, string ID_GUIA, string CO_USUA, string ST_PRE_DESPACHO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvPreDespacho/SetGeneraPreDespacho", ReplyAction="http://tempuri.org/IsrvPreDespacho/SetGeneraPreDespachoResponse")]
        bool SetGeneraPreDespacho(out UITalmaNET.srvPreDespacho.beLogger logger, string ID_GUIA, string CO_USUA, System.Nullable<System.DateTime> FE_RETI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvPreDespacho/GetPreFactura", ReplyAction="http://tempuri.org/IsrvPreDespacho/GetPreFacturaResponse")]
        System.Collections.Generic.List<UITalmaNET.srvPreDespacho.bePreFactura> GetPreFactura(out UITalmaNET.srvPreDespacho.beLogger logger, string ID_GUIA);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvPreDespacho/SetGeneraPreFactura", ReplyAction="http://tempuri.org/IsrvPreDespacho/SetGeneraPreFacturaResponse")]
        bool SetGeneraPreFactura(out UITalmaNET.srvPreDespacho.beLogger logger, string ID_GUIA, System.Nullable<System.DateTime> FE_SALI, string CO_USUA);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvPreDespacho/GetGetGuia_Resumen", ReplyAction="http://tempuri.org/IsrvPreDespacho/GetGetGuia_ResumenResponse")]
        System.Collections.Generic.List<UITalmaNET.srvPreDespacho.beGuia> GetGetGuia_Resumen(out UITalmaNET.srvPreDespacho.beLogger logger, string ID_GUIA);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvPreDespacho/GetTransacciones", ReplyAction="http://tempuri.org/IsrvPreDespacho/GetTransaccionesResponse")]
        System.Collections.Generic.List<UITalmaNET.srvPreDespacho.beTransaccion> GetTransacciones(out UITalmaNET.srvPreDespacho.beLogger logger, string ID_GUIA, int ID_ARCH);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvPreDespacho/UpSert_Transaccion", ReplyAction="http://tempuri.org/IsrvPreDespacho/UpSert_TransaccionResponse")]
        bool UpSert_Transaccion(out UITalmaNET.srvPreDespacho.beLogger logger, UITalmaNET.srvPreDespacho.beTransaccion be);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvPreDespacho/GetPreDespacho_Documentos", ReplyAction="http://tempuri.org/IsrvPreDespacho/GetPreDespacho_DocumentosResponse")]
        System.Collections.Generic.List<UITalmaNET.srvPreDespacho.bePreDespacho_Documento> GetPreDespacho_Documentos(out UITalmaNET.srvPreDespacho.beLogger logger, string ID_GUIA, int ID_ARCH);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvPreDespacho/UpSert_PreDespacho_Documento", ReplyAction="http://tempuri.org/IsrvPreDespacho/UpSert_PreDespacho_DocumentoResponse")]
        bool UpSert_PreDespacho_Documento(out UITalmaNET.srvPreDespacho.beLogger logger, UITalmaNET.srvPreDespacho.bePreDespacho_Documento be);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IsrvPreDespachoChannel : UITalmaNET.srvPreDespacho.IsrvPreDespacho, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IsrvPreDespachoClient : System.ServiceModel.ClientBase<UITalmaNET.srvPreDespacho.IsrvPreDespacho>, UITalmaNET.srvPreDespacho.IsrvPreDespacho {
        
        public IsrvPreDespachoClient() {
        }
        
        public IsrvPreDespachoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IsrvPreDespachoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IsrvPreDespachoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IsrvPreDespachoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<UITalmaNET.srvPreDespacho.bePreDespacho> GetPreDespachos(out UITalmaNET.srvPreDespacho.beLogger logger, string ID_GUIA, string CO_USUA, string ST_PRE_DESPACHO) {
            return base.Channel.GetPreDespachos(out logger, ID_GUIA, CO_USUA, ST_PRE_DESPACHO);
        }
        
        public bool SetGeneraPreDespacho(out UITalmaNET.srvPreDespacho.beLogger logger, string ID_GUIA, string CO_USUA, System.Nullable<System.DateTime> FE_RETI) {
            return base.Channel.SetGeneraPreDespacho(out logger, ID_GUIA, CO_USUA, FE_RETI);
        }
        
        public System.Collections.Generic.List<UITalmaNET.srvPreDespacho.bePreFactura> GetPreFactura(out UITalmaNET.srvPreDespacho.beLogger logger, string ID_GUIA) {
            return base.Channel.GetPreFactura(out logger, ID_GUIA);
        }
        
        public bool SetGeneraPreFactura(out UITalmaNET.srvPreDespacho.beLogger logger, string ID_GUIA, System.Nullable<System.DateTime> FE_SALI, string CO_USUA) {
            return base.Channel.SetGeneraPreFactura(out logger, ID_GUIA, FE_SALI, CO_USUA);
        }
        
        public System.Collections.Generic.List<UITalmaNET.srvPreDespacho.beGuia> GetGetGuia_Resumen(out UITalmaNET.srvPreDespacho.beLogger logger, string ID_GUIA) {
            return base.Channel.GetGetGuia_Resumen(out logger, ID_GUIA);
        }
        
        public System.Collections.Generic.List<UITalmaNET.srvPreDespacho.beTransaccion> GetTransacciones(out UITalmaNET.srvPreDespacho.beLogger logger, string ID_GUIA, int ID_ARCH) {
            return base.Channel.GetTransacciones(out logger, ID_GUIA, ID_ARCH);
        }
        
        public bool UpSert_Transaccion(out UITalmaNET.srvPreDespacho.beLogger logger, UITalmaNET.srvPreDespacho.beTransaccion be) {
            return base.Channel.UpSert_Transaccion(out logger, be);
        }
        
        public System.Collections.Generic.List<UITalmaNET.srvPreDespacho.bePreDespacho_Documento> GetPreDespacho_Documentos(out UITalmaNET.srvPreDespacho.beLogger logger, string ID_GUIA, int ID_ARCH) {
            return base.Channel.GetPreDespacho_Documentos(out logger, ID_GUIA, ID_ARCH);
        }
        
        public bool UpSert_PreDespacho_Documento(out UITalmaNET.srvPreDespacho.beLogger logger, UITalmaNET.srvPreDespacho.bePreDespacho_Documento be) {
            return base.Channel.UpSert_PreDespacho_Documento(out logger, be);
        }
    }
}
